name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          df -h

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            max-jobs = auto
            cores = 2
            
      - name: Setup Cachix (optional binary cache)
        uses: cachix/cachix-action@v12
        with:
          name: hydra-node
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with Nix
        run: |
          VERSION=$(git rev-parse --short HEAD)
          nix-build release.nix -A dockerImage \
            --argstr version $VERSION \
            --argstr name carlosa8c/hydra-pay

      - name: Load and push Docker image
        run: |
          VERSION=$(git rev-parse --short HEAD)
          docker load < result
          docker push carlosa8c/hydra-pay:$VERSION
          docker tag carlosa8c/hydra-pay:$VERSION carlosa8c/hydra-pay:latest
          docker push carlosa8c/hydra-pay:latest
